version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./data:/data
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  web:
    image: oneillkyle/farm-api:v1
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    command: python3 manage.py migrate && gunicorn farm_api.wsgi:application --bind 0.0.0.0:8000
    # command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api:/code
    ports:
      - "80:8000"
    depends_on:
      - db
    networks:
      - webnet
  # nginx:
  #   image: nginx
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d
  #   # volumes_from:
  #   #   - web
  #   ports:
  #     - "8000:8000"
  #   networks:
  #     - webnet
  #   depends_on:
  #     - web
networks:
  webnet:
